services:
  golang-app:
    image: ostepanyk/golang-demo
    ports:
      - "32555:8080"
    environment:
      - DB_PORT=5432
      - DB_ENDPOINT=db
      - DB_USER=postgres
      - DB_PASSWORD=1q2w3e4r
      - DB_NAME=db 
    command: "./golang-demo"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1q2w3e4r
    ports:
      - "5432:5432"
    volumes:
      - ./db_schema.sql:/docker-entrypoint-initdb.d/db_schema.sql
      - postgres_data:/var/lib/postgresql/data
  web:
    image: nginx:latest
    ports:
      - "32660:80"
    volumes:
      - ./default:/etc/nginx/conf.d/default.conf
    depends_on:
      - golang-app
volumes:
  postgres_data: