version: '3.8'

services:
  golang-app:
    build: .
    ports:
      - "32555:8080"
    volumes:
      - .:/app
    environment:
      - DB_PORT=5432
      - DB_ENDPOINT=db
      - DB_USER=postgres
      - DB_PASSWORD=1q2w3e4r
      - DB_NAME=db
    command: ["./golang-demo"]
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1q2w3e4r
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    image: nginx:latest
    ports:
      - "32660:80"
    volumes:
      - ./default:/etc/nginx/conf.d/default.conf
    depends_on:
      - golang-app
  temp-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1q2w3e4r
      PGPASSWORD: 1q2w3e4r
    command: "psql -h db -U postgres -d db -a -f /db_schema.sql"
    ports:
      - "5433:5433"
    volumes:
      - ./db_schema.sql:/db_schema.sql
    depends_on:
      - db
volumes:
  postgres_data: