apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: {{ .Values.golangApp.name }}
  name: {{ .Values.golangApp.name }}
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.golangApp.port }}
      targetPort: {{ .Values.golangApp.port }}
      nodePort: 32555
  selector:
    io.kompose.service: {{ .Values.golangApp.name }}
