apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data-volume
  labels:
    io.kompose.service: postgres-data-volume
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.postgres.pvcSize }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
