apiVersion: v1
data:
  default: |
    server {
        listen 80;

        location / {
            proxy_pass http://{{ .Values.golangApp.name }}:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: {{ .Values.nginx.name }}
  name: {{ .Values.nginx.configmapName }}
