apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: {{ .Values.nginx.name }}
  name: {{ .Values.nginx.name }}
spec:
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.nginx.name }}
  template:
    metadata:
      labels:
        io.kompose.service: {{ .Values.nginx.name }}
    spec:
      containers:
        - image: {{ .Values.nginx.image }}
          name: {{ .Values.nginx.name }}
          ports:
            - containerPort: {{ .Values.nginx.port }}
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              name: {{ .Values.nginx.configmapName }}
              subPath: default.conf
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: default
                path: default.conf
            name: {{ .Values.nginx.configmapName }}
          name: {{ .Values.nginx.configmapName }}
