name: Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/checkout@v3

  package-and-publish:
    needs:
      - build

    name: Package & Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Sign in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Generate Docker Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=tag
            type=ref,event=pr
            type=sha,event=branch,prefix=,suffix=,format=short

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  
  deploy:
    needs:
      - package-and-publish

    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Copy files to EC2
      uses: cross-the-world/scp-pipeline@master
      with:
       host: ${{ secrets.EC2_IP }}
       user: "ubuntu"
       key: ${{ secrets.PUB_KEY }}
       scp: |
         app.yaml => "/home/ubuntu/"
         nodeport.yaml => "/home/ubuntu/"
    - name: SSH to EC2
      uses: appleboy/ssh-action@v1.2.0
      with:
       host: ${{ secrets.EC2_IP }}
       username: "ubuntu"
       key: ${{ secrets.PUB_KEY }}
       script: |